# This is the sphinx configuration script to generate the COBEA documentation,
# it was distilled from autogenerated Sphinx output
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
]

templates_path = ['_templates']
source_suffix = '.rst'
master_doc = 'index'

project = u'COBEA'
copyright = u'2017, Bernard Riemann'
author = u'Bernard Riemann'

version = u'0.24'
release = version

language = None
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
pygments_style = 'sphinx'
todo_include_todos = False

latex_elements = {
     'papersize': 'a4paper',
}
latex_documents = [
    (master_doc, 'COBEA.tex', u'COBEA Manual',
     u'Bernard Riemann', 'manual'),
]

# man_pages = [
#     (master_doc, 'cobea', u'COBEA Documentation',
#      [author], 1)
# ]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
# texinfo_documents = [
#     (master_doc, 'COBEA', u'COBEA Documentation',
#      author, 'COBEA', 'One line description of project.',
#      'Miscellaneous'),
# ]
